"""Compile a validated WorkflowDoc into a native Workflow tool script (JavaScript).

The emitted script is exactly what the Workflow tool expects: an `export const
meta = {...}` literal followed by a body that calls agent()/parallel()/pipeline().
workflow-kit never executes anything itself -- the skill hands this string (via a
file) to the native Workflow tool, which runs it.

Mapping (see the skill / plan for the authoring format):
  - doc                      -> meta + body
  - schemas.NAME             -> `const schema_NAME = {...};`  passed as agent {schema}
  - (always)                 -> `const inputs = ...JSON.parse(args)...;`  (args arrives
                                as a JSON string in this runtime; inputs.X targets it)
  - agent step, no fan-out   -> `const VAR = await agent(...)`
  - agent step, for_each     -> `const VAR = await parallel(OVER.map((item) => () => agent(...)))`
  - pipeline step            -> `const VAR = await pipeline(OVER, stageFn, ...)`
      each stage callback is `(prev, AS, i) => agent(...)`; a stage with fan_out
      wraps its body in a nested `parallel(...)` (the canonical Workflow pattern).
  - script step              -> `const VAR = await wkScript(cmd, out, opts)`  (node strategy)
  - openrouter step          -> `const VAR = await wkOpenRouter(runner, spec, opts)`  (node strategy)
      script/openrouter steps inline preamble.js (wkScript/wkOpenRouter) once; both
      support for_each (fan-out indexes the default out path so payloads do not collide).
  - output                   -> `return EXPR;`  (default: object of all step results)
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .errors import WorkflowError
from .expr import Scope, compile_expr, compile_single, compile_template
from .model import WorkflowDoc, Step, Stage

_GENERATED_HEADER = (
    "// GENERATED by workflow-kit from a .workflow.yaml -- do not edit by hand.\n"
    "// Re-generate with: workflow-kit compile <file>.workflow.yaml\n"
)

PREV_VAR = "prev"  # name of the first param of every pipeline stage callback

# Runtime values the skill injects into `args` for node steps (never declared in
# `inputs:` -- see references/workflow-yaml.md "Reserved inputs"). They are valid
# `{{ inputs.* }}` heads only when the document actually has node steps.
RESERVED_NODE_INPUTS = {"runId", "pluginRoot", "workflowKitVenvPython"}

# The Workflow tool delivers the `args` global as a JSON string in this runtime,
# so the compiled script normalizes it once into a real object named `inputs`
# (what every {{ inputs.X }} expression compiles against). Harmless if a future
# runtime hands over a real object instead.
_ARGS_NORMALIZE = (
    'const inputs = typeof args === "string" ? JSON.parse(args) : (args || {});'
)


def _var(step_id: str) -> str:
    return "step_" + re.sub(r"[^A-Za-z0-9_]", "_", step_id)


def _phase_table(doc: WorkflowDoc):
    """Return (ordered [(id, title)], {id: title}) merging declared + inferred phases."""
    ordered = []
    by_id = {}
    for p in doc.phases:
        if p.id not in by_id:
            by_id[p.id] = p.title
            ordered.append((p.id, p.title))

    def add(pid):
        if pid and pid not in by_id:
            by_id[pid] = pid
            ordered.append((pid, pid))

    for step in doc.steps:
        add(step.phase)
        if step.is_pipeline:
            for stage in step.pipeline.stages:
                add(stage.phase)
    return ordered, by_id


def _agent_call(agent, phase_id, scope: Scope, phase_titles: dict) -> str:
    prompt_js = compile_template(agent.prompt, scope)
    opts = []
    if agent.schema:
        opts.append(f"schema: schema_{agent.schema}")
    if phase_id:
        opts.append(f"phase: {json.dumps(phase_titles[phase_id])}")
    if agent.model:
        opts.append(f"model: {json.dumps(agent.model)}")
    if agent.agentType:
        opts.append(f"agentType: {json.dumps(agent.agentType)}")
    if agent.isolation:
        opts.append(f"isolation: {json.dumps(agent.isolation)}")
    if agent.label:
        opts.append(f"label: {json.dumps(agent.label)}")
    if opts:
        return f"agent({prompt_js}, {{ {', '.join(opts)} }})"
    return f"agent({prompt_js})"


def _over_js(over, scope: Scope) -> str:
    if isinstance(over, list):
        return json.dumps(over)
    return compile_single(over, scope)


# --------------------------------------------------------------------------- #
# node strategies (script / openrouter) -- compile to the inlined preamble
# helpers wkScript / wkOpenRouter, which run via the workflow-kit-agent executor.
# --------------------------------------------------------------------------- #
def _load_preamble() -> str:
    """Read the node-strategy preamble (wkNode/wkScript/wkOpenRouter) for inlining.

    Sandboxed Workflow scripts cannot import, so the helpers are spliced into the
    compiled output verbatim. The preamble is the single source of truth and ships
    with the plugin's skill alongside this package.
    """
    p = (
        Path(__file__).resolve().parent.parent
        / "skills" / "workflow-kit" / "references" / "preamble.js"
    )
    try:
        return p.read_text(encoding="utf-8").rstrip("\n")
    except OSError as exc:
        raise WorkflowError(f"cannot read node-strategy preamble at {p}: {exc}")


def _safe_id(step_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", step_id)


def _default_out_js(step_id: str, suffix: str, fanout: bool) -> str:
    """Default `$OUT` path as a JS template literal under ./.workflow-kit/<runId>/."""
    base = f"./.workflow-kit/${{inputs.runId}}/{_safe_id(step_id)}"
    return f"`{base}.${{i}}{suffix}`" if fanout else f"`{base}{suffix}`"


def _node_opts(label, phase_id, phase_titles, status_js=None) -> str:
    parts = []
    if label:
        parts.append(f"label: {json.dumps(label)}")
    if phase_id:
        parts.append(f"phase: {json.dumps(phase_titles[phase_id])}")
    if status_js:
        parts.append(f"status: {status_js}")
    return "{ " + ", ".join(parts) + " }" if parts else "{}"


def _node_scope(step: Step, defined: dict, inputs: set):
    """(scope, over_js|None) for a node step, honoring an optional flat for_each."""
    base = Scope(step_vars=defined, inputs=inputs)
    if step.for_each is None:
        return base, None
    over_js = _over_js(step.for_each, base)
    return Scope(step_vars=defined, locals={"item": "item"}, inputs=inputs), over_js


def _wrap_node(var: str, call: str, over_js) -> str:
    if over_js is None:
        return f"const {var} = await {call};"
    # fan-out: `i` indexes the default out path so payloads do not collide.
    return f"const {var} = await parallel({over_js}.map((item, i) => () => {call}));"


def _emit_script_node(step: Step, defined: dict, phase_titles: dict, inputs: set) -> str:
    sp = step.script
    scope, over_js = _node_scope(step, defined, inputs)
    fan = over_js is not None
    cmd_js = compile_template(sp.command, scope)
    out_js = compile_template(sp.out, scope) if sp.out else _default_out_js(step.id, ".out", fan)
    status_js = compile_template(sp.status, scope) if sp.status else None
    opts = _node_opts(sp.label, step.phase, phase_titles, status_js)
    call = f"wkScript({cmd_js}, {out_js}, {opts})"
    return _wrap_node(_var(step.id), call, over_js)


def _emit_openrouter_node(step: Step, defined: dict, phase_titles: dict, inputs: set) -> str:
    op = step.openrouter
    scope, over_js = _node_scope(step, defined, inputs)
    fan = over_js is not None
    runner_js = (
        '`"${inputs.workflowKitVenvPython}" '
        '"${inputs.pluginRoot}/scripts/openrouter_run.py"`'
    )
    out_js = compile_template(op.out, scope) if op.out else _default_out_js(step.id, ".out", fan)
    spec = []
    if op.model:
        spec.append(f"model: {json.dumps(op.model)}")
    if op.cheap:
        spec.append("cheap: true")
    spec.append(f"promptFile: {compile_template(op.prompt_file, scope)}")
    if op.system is not None:
        spec.append(f"system: {compile_template(op.system, scope)}")
    spec.append(f"out: {out_js}")
    if op.status:
        spec.append(f"status: {compile_template(op.status, scope)}")
    spec_js = "{ " + ", ".join(spec) + " }"
    opts = _node_opts(op.label, step.phase, phase_titles)
    call = f"wkOpenRouter({runner_js}, {spec_js}, {opts})"
    return _wrap_node(_var(step.id), call, over_js)


def _emit_flat_step(step: Step, defined: dict, phase_titles: dict, inputs: set) -> str:
    var = _var(step.id)
    if step.for_each is None:
        scope = Scope(step_vars=defined, inputs=inputs)
        call = _agent_call(step.agent, step.phase, scope, phase_titles)
        return f"const {var} = await {call};"
    # fan-out: parallel over a list, item bound to `item`
    over_js = _over_js(step.for_each, Scope(step_vars=defined, inputs=inputs))
    inner = Scope(step_vars=defined, locals={"item": "item"}, inputs=inputs)
    call = _agent_call(step.agent, step.phase, inner, phase_titles)
    return f"const {var} = await parallel({over_js}.map((item) => () => {call}));"


def _emit_stage_callback(
    stage: Stage, as_name: str, prev_stage_id, defined: dict, phase_titles: dict,
    inputs: set,
) -> str:
    prev = (prev_stage_id, PREV_VAR) if prev_stage_id else None
    if stage.fan_out is not None:
        fan = stage.fan_out
        over_scope = Scope(
            step_vars=defined, locals={as_name: as_name}, prev_stage=prev, inputs=inputs
        )
        over_js = _over_js(fan.over, over_scope)
        body_scope = Scope(
            step_vars=defined,
            locals={as_name: as_name, fan.as_: fan.as_},
            prev_stage=prev,
            inputs=inputs,
        )
        call = _agent_call(stage.agent, stage.phase, body_scope, phase_titles)
        body = f"parallel({over_js}.map(({fan.as_}) => () => {call}))"
    else:
        scope = Scope(
            step_vars=defined, locals={as_name: as_name}, prev_stage=prev, inputs=inputs
        )
        body = _agent_call(stage.agent, stage.phase, scope, phase_titles)
    return f"({PREV_VAR}, {as_name}, i) => {body}"


def _emit_pipeline_step(step: Step, defined: dict, phase_titles: dict, inputs: set) -> str:
    var = _var(step.id)
    pipe = step.pipeline
    over_js = _over_js(pipe.over, Scope(step_vars=defined, inputs=inputs))
    callbacks = []
    prev_id = None
    for stage in pipe.stages:
        callbacks.append(
            _emit_stage_callback(stage, pipe.as_, prev_id, defined, phase_titles, inputs)
        )
        prev_id = stage.id
    cb_block = ",\n  ".join(callbacks)
    return f"const {var} = await pipeline(\n  {over_js},\n  {cb_block},\n);"


def _emit_output(doc: WorkflowDoc, defined: dict, inputs: set) -> str:
    if doc.output:
        expr = compile_single(doc.output, Scope(step_vars=defined, inputs=inputs))
        return f"return {expr};"
    parts = ", ".join(f"{json.dumps(s.id)}: {_var(s.id)}" for s in doc.steps)
    return f"return {{ {parts} }};"


def compile_doc(doc: WorkflowDoc) -> str:
    """Compile a validated WorkflowDoc to a native Workflow tool JS script."""
    ordered_phases, phase_titles = _phase_table(doc)
    has_nodes = any(s.kind in ("script", "openrouter") for s in doc.steps)
    # `inputs.*` heads every Scope checks against: the declared `inputs:` names,
    # plus the skill-injected reserved args -- but only when node steps exist.
    allowed_inputs = set(doc.inputs) | (RESERVED_NODE_INPUTS if has_nodes else set())

    lines = [_GENERATED_HEADER]

    # meta
    meta_phases = ",\n    ".join(
        f"{{ title: {json.dumps(title)} }}" for _id, title in ordered_phases
    )
    meta = [
        "export const meta = {",
        f"  name: {json.dumps(doc.name)},",
        f"  description: {json.dumps(doc.description)},",
        f"  phases: [\n    {meta_phases}\n  ]," if ordered_phases else "  phases: [],",
        "};",
    ]
    lines.append("\n".join(meta))

    # inputs documentation (the engine exposes them as the `args` global)
    if doc.inputs:
        doc_lines = "\n".join(
            f"//   args.{name}: {spec.type}"
            + (f" -- {spec.description}" if spec.description else "")
            for name, spec in doc.inputs.items()
        )
        lines.append("// Inputs (provided via the Workflow `args` global):\n" + doc_lines)

    # schema consts
    if doc.schemas:
        schema_lines = []
        for name, body in doc.schemas.items():
            schema_lines.append(f"const schema_{name} = {json.dumps(body, indent=2)};")
        lines.append("\n".join(schema_lines))

    # normalize args (the Workflow tool delivers `args` as a JSON string)
    lines.append(_ARGS_NORMALIZE)

    # inline the node-strategy preamble when any script/openrouter node is present
    if has_nodes:
        lines.append(_load_preamble())

    # body
    defined = {}
    body = []
    for step in doc.steps:
        kind = step.kind
        if kind == "pipeline":
            body.append(_emit_pipeline_step(step, defined, phase_titles, allowed_inputs))
        elif kind == "script":
            body.append(_emit_script_node(step, defined, phase_titles, allowed_inputs))
        elif kind == "openrouter":
            body.append(_emit_openrouter_node(step, defined, phase_titles, allowed_inputs))
        else:
            body.append(_emit_flat_step(step, defined, phase_titles, allowed_inputs))
        defined[step.id] = _var(step.id)
    body.append(_emit_output(doc, defined, allowed_inputs))
    lines.append("\n".join(body))

    return "\n\n".join(lines) + "\n"
