"""Direct tests for the public-repo pre-commit guard (no Git process)."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "precommit_guard.py"
SPEC = importlib.util.spec_from_file_location("precommit_guard", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
guard = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = guard
SPEC.loader.exec_module(guard)


def rules(violations):
    return {violation.rule for violation in violations}


def test_size_rule_blocks_over_one_megabyte():
    violations = guard.inspect_file(
        "large.bin", guard.MAX_STAGED_FILE_BYTES + 1, None, set(), []
    )
    assert rules(violations) == {"size"}


def test_manifest_target_rule_blocks_exact_path():
    target = "plugins/sample/generated/output.py"
    violations = guard.inspect_file(target, 4, b"safe", {target}, [])
    assert rules(violations) == {"bootstrap write target"}


def test_generated_by_banner_is_blocked():
    violations = guard.inspect_file(
        "artifact.py", 24, b"# Generated by a tool\n", set(), []
    )
    assert rules(violations) == {"generated artifact"}


def test_unreal_stub_header_is_blocked():
    content = b"from __future__ import annotations\n\n##### Glue Code #####\n"
    violations = guard.inspect_file("stub.py", len(content), content, set(), [])
    assert rules(violations) == {"generated artifact"}


def test_normal_small_file_passes():
    assert guard.inspect_file("notes.txt", 6, b"hello\n", set(), []) == []


def test_local_term_matches_path_or_content():
    terms = guard.parse_local_terms("# local only\nNeedle\n")
    assert terms == ["needle"]
    violations = guard.inspect_file("notes.txt", 12, b"has NEEDLE\n", set(), terms)
    assert rules(violations) == {"local term"}


def test_absent_local_term_file_is_explicitly_disabled():
    missing = ROOT / "tmp" / "precommit-guard-term-file-does-not-exist.txt"
    assert guard.load_local_terms(missing) is None
    assert guard.disabled_terms_message() == (
        "pre-commit: optional term checks disabled; no "
        ".githooks/project-terms.txt found."
    )


def test_manifest_targets_include_extract_and_custom_copy_destinations():
    manifest_path = "plugins/sample/bootstrap.json"
    manifest = {
        "pypi_packages": [
            {
                "package": "sample",
                "extract_to": "${plugin_root}/generated/from-wheel.py",
            }
        ],
        "script": {"path": "custom_bootstrap.py", "entry_point": "bootstrap"},
    }
    script = b"""
from pathlib import Path
import shutil
def bootstrap(ctx):
    destination = Path(ctx.plugin_root) / "generated" / "from-project.py"
    shutil.copy2("source.py", destination)
"""
    targets = guard.manifest_write_targets(
        {manifest_path: json.dumps(manifest).encode("utf-8")},
        lambda path: script,
    )
    assert targets == {
        "plugins/sample/generated/from-wheel.py",
        "plugins/sample/generated/from-project.py",
    }


def test_repo_unreal_manifest_maps_plugin_root_to_repo_path():
    manifest_path = "plugins/unreal-kit/bootstrap.json"
    source = (ROOT / manifest_path).read_bytes()

    def load_script(repo_path: str) -> bytes:
        return (ROOT / repo_path).read_bytes()

    targets = guard.manifest_write_targets({manifest_path: source}, load_script)
    assert "plugins/unreal-kit/skills/ue-python-api/stubs/unreal.py" in targets


def test_refusal_message_states_principle_doc_and_override():
    message = guard.refusal_message(
        [guard.Violation("size", "large.bin", "too large")]
    )
    assert "plugins-kit is a public repo" in message
    assert str(guard.PATTERN_DOC) in message
    assert guard.OVERRIDE_ENV in message
