"""Direct tests for the public-repo pre-commit guard (no Git process)."""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "precommit_guard.py"
SPEC = importlib.util.spec_from_file_location("precommit_guard", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
guard = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = guard
SPEC.loader.exec_module(guard)


def rules(violations):
    return {violation.rule for violation in violations}


def test_size_rule_blocks_over_one_megabyte():
    violations = guard.inspect_file(
        "large.bin", guard.MAX_STAGED_FILE_BYTES + 1, None, set(), []
    )
    assert rules(violations) == {"size"}


def test_manifest_target_rule_blocks_exact_path():
    target = "plugins/sample/generated/output.py"
    violations = guard.inspect_file(target, 4, b"safe", {target}, [])
    assert rules(violations) == {"bootstrap write target"}


def test_generated_by_banner_is_blocked():
    violations = guard.inspect_file(
        "artifact.py", 24, b"# Generated by a tool\n", set(), []
    )
    assert rules(violations) == {"generated artifact"}


def test_guard_shares_the_code_review_signature_list():
    """One signature list, two callers.

    The guard and bootstrap_lib.code_review.pipeline both answer "did a tool
    write this file?" -- from bootstrap_lib.code_review.machine_emitted. A second copy
    here would drift and let a file be refused at commit time while still being
    fanned out to reviewers, or the reverse. These two shapes exist only in the
    shared list, so they fail if the guard ever grows its own.
    """
    at_generated = b" * @" + b"generated\n"
    assert rules(guard.inspect_file("a.js", 14, at_generated, set(), [])) == {
        "generated artifact"
    }
    shouted = b"# DO NOT " + b"EDIT -- rebuild instead\n"
    assert rules(guard.inspect_file("b.py", 30, shouted, set(), [])) == {
        "generated artifact"
    }


def test_instructional_prose_is_not_a_generated_banner():
    content = b"# Do not edit it in place: it lives inside the plugin.\n"
    assert guard.inspect_file("defaults.yaml", len(content), content, set(), []) == []


def test_unreal_stub_header_is_blocked():
    content = b"from __future__ import annotations\n\n##### Glue Code #####\n"
    violations = guard.inspect_file("stub.py", len(content), content, set(), [])
    assert rules(violations) == {"generated artifact"}


def test_normal_small_file_passes():
    assert guard.inspect_file("notes.txt", 6, b"hello\n", set(), []) == []


def test_local_term_matches_path_or_content():
    terms = guard.parse_local_terms("# local only\nNeedle\n")
    assert terms == ["needle"]
    violations = guard.inspect_file("notes.txt", 12, b"has NEEDLE\n", set(), terms)
    assert rules(violations) == {"local term"}


def test_absent_local_term_file_is_explicitly_disabled():
    missing = ROOT / "tmp" / "precommit-guard-term-file-does-not-exist.txt"
    assert guard.load_local_terms(missing) is None
    assert guard.disabled_terms_message() == (
        "pre-commit: optional term checks disabled; no "
        ".githooks/project-terms.txt found."
    )


def test_manifest_targets_include_extract_and_custom_copy_destinations():
    manifest_path = "plugins/sample/bootstrap.json"
    manifest = {
        "pypi_packages": [
            {
                "package": "sample",
                "extract_to": "${plugin_root}/generated/from-wheel.py",
            }
        ],
        "script": {"path": "custom_bootstrap.py", "entry_point": "bootstrap"},
    }
    script = b"""
from pathlib import Path
import shutil
def bootstrap(ctx):
    destination = Path(ctx.plugin_root) / "generated" / "from-project.py"
    shutil.copy2("source.py", destination)
"""
    targets = guard.manifest_write_targets(
        {manifest_path: json.dumps(manifest).encode("utf-8")},
        lambda path: script,
    )
    assert targets == {
        "plugins/sample/generated/from-wheel.py",
        "plugins/sample/generated/from-project.py",
    }


def test_repo_unreal_manifest_has_no_repo_write_target():
    manifest_path = "plugins/unreal-kit/bootstrap.json"
    source = (ROOT / manifest_path).read_bytes()

    def load_script(repo_path: str) -> bytes:
        return (ROOT / repo_path).read_bytes()

    targets = guard.manifest_write_targets({manifest_path: source}, load_script)
    assert targets == set()


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        check=True,
        text=True,
    )


def _detector_source(label: str) -> str:
    """A minimal stand-in detector, distinguishable by the label it returns."""
    return (
        "def detect_signature_bytes(data):\n"
        f"    return {label!r} if b'MARK' in data else None\n"
    )


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    """A throwaway repo. Never touches the real index -- see CLAUDE.md."""
    work = tmp_path / "repo"
    (work / "scripts").mkdir(parents=True)
    _git(tmp_path, "init", "-q", str(work))
    _git(work, "config", "user.email", "guard@test")
    _git(work, "config", "user.name", "guard test")
    for candidate in guard.DETECTOR_CANDIDATES:
        (work / candidate).parent.mkdir(parents=True, exist_ok=True)
    head_name = guard.DETECTOR_CANDIDATES[-1]  # the older name
    (work / head_name).write_text(_detector_source("from-HEAD"), encoding="utf-8")
    _git(work, "add", "-A")
    _git(work, "commit", "-qm", "init")
    return work


def test_detector_is_loaded_from_the_index_when_staged(repo: Path):
    """A commit that changes the signature list is judged by its OWN version."""
    path = repo / guard.DETECTOR_CANDIDATES[-1]
    path.write_text(_detector_source("from-index"), encoding="utf-8")
    _git(repo, "add", str(path))
    path.write_text("raise RuntimeError('worktree is half-applied')\n", encoding="utf-8")

    detect = guard.load_detector(repo)

    assert detect(b"MARK") == "from-index"


def test_staged_rename_beats_the_stale_head_copy_of_the_old_name(repo: Path):
    """Index is tried for EVERY candidate before HEAD is tried for any."""
    old = repo / guard.DETECTOR_CANDIDATES[-1]
    new = repo / guard.DETECTOR_CANDIDATES[0]
    new.write_text(_detector_source("renamed-and-staged"), encoding="utf-8")
    old.unlink()
    _git(repo, "add", "-A")

    assert guard.load_detector(repo)(b"MARK") == "renamed-and-staged"


def test_detector_falls_back_to_head_when_not_staged(repo: Path):
    """The worktree copy is renamed away and nothing is staged: HEAD answers."""
    old = repo / guard.DETECTOR_CANDIDATES[-1]
    old.rename(repo / guard.DETECTOR_CANDIDATES[0])

    detect = guard.load_detector(repo)

    assert detect(b"MARK") == "from-HEAD"


def test_unloadable_detector_raises_inspection_error_naming_the_files(repo: Path):
    with pytest.raises(guard.GuardInspectionError) as excinfo:
        guard.load_detector(repo, candidates=("plugins/nope/missing_detector.py",))
    message = str(excinfo.value)
    assert "could not load" in message
    assert "plugins/nope/missing_detector.py" in message


def test_broken_staged_detector_still_refuses_rather_than_passing(repo: Path):
    """A genuinely broken STAGED detector must refuse, never fail open."""
    only = "plugins/bootstrap/bootstrap_lib/code_review/machine_emitted.py"
    (repo / only).write_text("def detect_signature_bytes(  # truncated\n", encoding="utf-8")
    _git(repo, "add", "-A")
    with pytest.raises(guard.GuardInspectionError) as excinfo:
        guard.load_detector(repo, candidates=(only,))
    assert "SyntaxError" in str(excinfo.value)


def _run_guard(repo: Path) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env.pop(guard.OVERRIDE_ENV, None)
    return subprocess.run(
        [sys.executable, str(SCRIPT)],
        cwd=str(repo),
        capture_output=True,
        text=True,
        env=env,
    )


def test_cli_survives_a_half_applied_worktree_rename(repo: Path):
    """The 2026-08-09 outage: another session's UNSTAGED rename broke everyone."""
    (repo / guard.DETECTOR_CANDIDATES[-1]).rename(repo / guard.DETECTOR_CANDIDATES[0])
    (repo / "notes.txt").write_text("ordinary work\n", encoding="utf-8")
    _git(repo, "add", "notes.txt")

    result = _run_guard(repo)

    assert result.returncode == 0, result.stderr
    assert "Traceback" not in result.stderr


def test_cli_refuses_cleanly_when_the_detector_cannot_be_loaded(repo: Path):
    _git(repo, "rm", "-q", "--cached", guard.DETECTOR_CANDIDATES[-1])
    _git(repo, "commit", "-qm", "drop the detector")
    (repo / "notes.txt").write_text("ordinary work\n", encoding="utf-8")
    _git(repo, "add", "notes.txt")

    result = _run_guard(repo)

    assert result.returncode == 1
    assert "Traceback" not in result.stderr
    assert "guard inspection failed" in result.stderr
    assert "NOT a detected violation" in result.stderr
    assert guard.DETECTOR_CANDIDATES[0] in result.stderr
    assert guard.OVERRIDE_ENV in result.stderr


def test_cli_still_catches_a_real_violation(repo: Path):
    # The fixture's stand-in detector flags any file containing MARK, so this
    # asserts the detection PATH end to end without re-testing the real list
    # (which the inspect_file tests above already cover).
    (repo / "artifact.py").write_text("MARK\n", encoding="utf-8")
    _git(repo, "add", "artifact.py")

    result = _run_guard(repo)

    assert result.returncode == 1
    assert "Traceback" not in result.stderr
    assert "generated artifact: artifact.py (from-HEAD)" in result.stderr


def test_refusal_message_states_principle_doc_and_override():
    message = guard.refusal_message(
        [guard.Violation("size", "large.bin", "too large")]
    )
    assert "plugins-kit is a public repo" in message
    assert str(guard.PATTERN_DOC) in message
    assert guard.OVERRIDE_ENV in message
