"""The VcsBackend protocol.

Every VCS backend (``null_vcs``, ``git_vcs``, and p4-kit's Perforce
implementation of this same protocol) exposes this exact surface, so
``deliver`` can drive changeset choreography without knowing which backend
is configured: ``open_for_edit``, ``add``, ``make_changeset``, ``move_into``,
``finalize_description``, ``revert``, ``delete_if_empty``.
"""

from typing import Protocol


class VcsBackend(Protocol):
    def open_for_edit(self, path) -> None: ...
    def add(self, path) -> None: ...
    def make_changeset(self, description: str): ...
    def move_into(self, changeset, paths: list) -> None: ...
    def finalize_description(self, changeset, description: str) -> None: ...
    def revert(self, path) -> None: ...
    def delete_if_empty(self, changeset) -> None: ...
