"""Machine-emitted-artifact detection: the ONE signature list this repo recognizes.

Two callers, one source of truth:

- ``pipeline.assemble_bundle`` -- a machine-emitted file is excluded from the
  reviewer chunks entirely and surfaced under ``machine_emitted_files``.
  Reviewing it is waste: nobody wrote a line of it, and the only meaningful
  review target is the GENERATOR, which is reviewed separately as ordinary
  source. A single multi-megabyte artifact otherwise becomes dozens of chunks
  times R reviewers.
- the repo's pre-commit guard (``scripts/precommit_guard.py``), which refuses to
  commit such a file into a public repo.

Both answer the same question ("did a tool write this file?"), so they must
answer it identically; a second drifting list would let a file be refused at
commit time but fanned out to reviewers, or the reverse.

Detection is CONTENT-first and never size-alone. A large hand-written file must
still be fully reviewed -- size is evidence of nothing. Every signature is a
BANNER shape anchored at the start of a line (a comment marker plus a
conventional phrase), so prose that merely talks about generated files does not
match.
"""

import re
from pathlib import Path
from typing import Optional

# Lines a generated banner is expected to appear within, counted from the start
# of the file (or of a diff section's added content).
DEFAULT_HEAD_LINES = 40

# Cap on how much of an on-disk file is read for the head scan. A machine-emitted
# artifact can be tens of megabytes; only its opening matters.
LOCAL_HEAD_BYTES = 64 * 1024

# Comment-marker alternation shared by the banner signatures. The marker is what
# keeps a sentence of prose about generated files from matching.
_MARK = r"(?:#|//|--|;|<!--|/\*|\*)"

# Observed artifact banners, not a speculative vocabulary. Each entry is
# (label, pattern); the label is reported verbatim to the user, so it must read
# as an explanation ("why was this file not reviewed?").
SIGNATURES: tuple[tuple[str, str], ...] = (
    ("generated-by banner", rf"(?im)^[ \t]*{_MARK}[ \t]*(?:auto[- ])?generated by\b"),
    # `@generated` is unambiguous on its own, so the marker is optional here.
    ("at-generated marker", rf"(?m)^[ \t]*{_MARK}?[ \t]*@generated\b"),
    (
        "auto-generated banner",
        rf"(?im)^[ \t]*{_MARK}[ \t]*(?:this file (?:is|was) )?auto[- ]?generated\b",
    ),
    # Case-SENSITIVE: the shouted form is the banner convention, while mixed-case
    # "Do not edit ..." is ordinary instructional prose that must not match.
    (
        "do-not-edit banner",
        rf"(?m)^[ \t]*{_MARK}[ \t]*[^\n]{{0,60}}?\bDO NOT (?:EDIT|MODIFY)\b",
    ),
    ("Unreal Python stub header", r"(?m)^##### Glue Code #####$"),
    ("protobuf descriptor block", r"(?m)^_sym_db = _symbol_database\.Default\(\)$"),
)

_COMPILED: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (label, re.compile(pattern)) for label, pattern in SIGNATURES
)
_COMPILED_BYTES: tuple[tuple[str, re.Pattern[bytes]], ...] = tuple(
    (label, re.compile(pattern.encode("utf-8"))) for label, pattern in SIGNATURES
)


def detect_signature(text: str) -> Optional[str]:
    """Return the label of the first matching signature, or None."""
    for label, pattern in _COMPILED:
        if pattern.search(text):
            return label
    return None


def detect_signature_bytes(data: bytes) -> Optional[str]:
    """Bytes counterpart of `detect_signature` (for a VCS blob).

    Kept as a separate compiled set rather than decoding the input: the callers
    that hold bytes hold whole files, which may be large or not valid UTF-8.
    """
    for label, pattern in _COMPILED_BYTES:
        if pattern.search(data):
            return label
    return None


def added_head(section_text: str, max_lines: int = DEFAULT_HEAD_LINES) -> str:
    """The first `max_lines` ADDED lines of a unified-diff section, `+` stripped.

    File headers (`+++ b/...`) are not content and are skipped. For an added
    file the added lines ARE the file's opening, which is where a banner lives.
    """
    out: list[str] = []
    for line in section_text.splitlines():
        if not line.startswith("+") or line.startswith("+++"):
            continue
        out.append(line[1:])
        if len(out) >= max_lines:
            break
    return "\n".join(out)


def local_head(
    local: Optional[str],
    max_lines: int = DEFAULT_HEAD_LINES,
    max_bytes: int = LOCAL_HEAD_BYTES,
) -> str:
    """The first `max_lines` lines of the file at `local`, or '' if unreadable.

    Needed because a MODIFIED machine-emitted file's diff can start thousands of
    lines below its banner -- the added-content scan alone would miss it and fan
    the artifact out to the reviewers anyway.
    """
    if not local:
        return ""
    try:
        with open(local, "rb") as handle:
            raw = handle.read(max_bytes)
    except OSError:
        return ""
    text = raw.decode("utf-8", errors="replace")
    return "\n".join(text.splitlines()[:max_lines])


def local_size(local: Optional[str]) -> Optional[int]:
    """Byte size of the file at `local`, or None when it cannot be stat'ed."""
    if not local:
        return None
    try:
        return Path(local).stat().st_size
    except OSError:
        return None


def detect_machine_emitted(
    section_text: str,
    local: Optional[str] = None,
    max_lines: int = DEFAULT_HEAD_LINES,
) -> Optional[str]:
    """Signature label if this changed file is machine-emitted, else None.

    Scans the leading ADDED lines of the diff section first (which covers an
    added file, and a deleted or workspace-less one where nothing is on disk),
    then the leading lines of the file on disk (which covers a modified one).
    """
    label = detect_signature(added_head(section_text, max_lines))
    if label:
        return label
    return detect_signature(local_head(local, max_lines))
