#!/usr/bin/env bash
# pre-commit-version-check.sh — Block commits when marketplace.json is out of
# sync with the per-plugin plugin.json files it is derived from.
#
# marketplace.json's plugins[] array is regenerated by scripts/regen_marketplace.py.
# Editing marketplace.json by hand and committing is not the workflow; bump the
# version (or description, etc.) in plugins/<name>/.claude-plugin/plugin.json
# and re-run the regenerator. Subsumes the old version-only check: a version
# mismatch is just one kind of drift the regenerator surfaces.
#
# Install: ln -sf ../../scripts/pre-commit-version-check.sh .git/hooks/pre-commit

set -euo pipefail

# Resolve via git (works whether the hook is installed as a symlink, a copy, or
# wired via core.hooksPath). Falling back to $0-relative resolution would give
# the wrong directory when the hook is a symlink at .git/hooks/pre-commit.
REPO_ROOT="$(git rev-parse --show-toplevel)"

if ! uv run python "$REPO_ROOT/scripts/regen_marketplace.py" --check; then
    echo ""
    echo "Bump versions / descriptions in plugins/<name>/.claude-plugin/plugin.json,"
    echo "run \`python scripts/regen_marketplace.py\`, stage the result, and commit."
    exit 1
fi

# Staged-diff gate: plugin code/manifest changes need a staged version bump
# (escape hatch: PLUGINS_KIT_SKIP_BUMP_CHECK=1, or --no-verify). Details and
# rationale in the script header.
"$REPO_ROOT/scripts/check-staged-version-bump.sh"

# Companion to the gate above: that one forces plugin.json to be bumped, and
# nothing pulled pyproject.toml along with it -- which is how bootstrap's stated
# version drifted across five releases while a test that would have caught it
# sat un-run. Same escape hatch. Rationale in the script header.
uv run python "$REPO_ROOT/scripts/check_pyproject_sync.py"

# Manifest invariant: a plugin that ships a bootstrap.json must declare
# "bootstrap" in its plugin.json dependencies (CLAUDE.md, "Plugin dependencies
# on bootstrap") -- otherwise a user can install it without bootstrap and its
# manifest is never processed. Same escape hatch. Rationale in the script header.
uv run python "$REPO_ROOT/scripts/check_bootstrap_dependency.py"

# Derivation invariant: the DECISION half of the orchestrate skill's
# orchestration.yaml is derived one-way from the principles under
# plugins/awesome-kit/skills/orchestrate/references/. Blocks a derived-data
# edit that carries no corresponding principles change. Same escape hatch.
# Rationale, and an honest statement of what it does NOT guarantee, in the
# script header.
uv run python "$REPO_ROOT/scripts/check_orchestration_drift.py"
